### ISSUE TITLE
Add script initialize.py

### ISSUE THREAD

**Issue by kudkudak** [gmum/mlls2015#124]
- Wzorowac chembl_baselines initialize.py

Wynik: zapisane datasety

**Comment by igorsieradzki** [comment]
https://github.com/gmum/transferchem/blob/master/src/scripts/data/initialize.py
https://github.com/gmum/transferchem/blob/master/src/scripts/data/featurize_fingerprint.py

**Comment by igorsieradzki** [comment]
Done: https://github.com/gmum/mlls2015/blob/res/dataset/initlialize.py

**Comment by kudkudak** [comment]
Ha! Jest .save_meta :D (@lesniak in your face, widzisz - Igor to wymyślił niezależnie, nie da sie życ bez meta..)

**Comment by kudkudak** [comment]
Dopisalbys komentarze co robi ten kod dalej co tam robi jakies thresholdy odleglosci?

**Comment by kudkudak** [comment]
Wyglada super ogolnie, czuje sie taki szczesliwy ze mamy porzadne datasety od teraz ^^

**Comment by igorsieradzki** [comment]
Tak właśnie myślałem, że to może być tajemnicze, bo zmieniłem stały treshold na "dynamiczny".

**Comment by igorsieradzki** [comment]
Dopisałem, ale ciągle nie jest pewny czy to wyjaśnia.

Poprzedni kod (https://github.com/gmum/mlls2015/blob/dev/scripts/calculate_clustering.py#L136) miał na stałe ten treshold na 0.05, a są datasety dla których te odległości `min_distances` (na MolPrint2D) nie schodzą poniżej np. 0.20, wtedy kod odpowiedzialny na wybieranie klastra

```
probability_finding_very_close = [sum(x <= very_close_threshold)/float(x.shape[0]) for x in min_distances]
best_candidate_idx = np.argmin(probability_finding_very_close)
```

dawał w `probability_finding_very_close` same zera i wybierany był pierwszy klaster z brzegu.

**Comment by kudkudak** [comment]
Sounds good, dzieki

Pozdrawiam,
Stanislaw Jastrzębski

W dniu 6 października 2016 13:00 użytkownik Igor Sieradzki <
notifications@github.com> napisał:
