### ISSUE TITLE
Run first experiments and analyze first results

### ISSUE THREAD

**Issue by kudkudak** [gmum/mlls2015#88]
Sanity checks:
- We are not picking extreme hyperparameter values (model hyperparameters)
- Is computationally ok (do we have have any computational bottleneck?)
- Check if memory usage is a problem
- Add plotting functions
- Curves of different strategies meet in single point
- Repeatitive 
- All strategies (including CSJ)

**Comment by igorsieradzki** [comment]
- Picking extreme parametrs checked, none were picked
- Computationally it looks ok, most of the iteration time is used for fitting grid search (see below)
- No memory issues as of now
- Added plotting functions for curves and times charts
- Checked that same experiment params yield same results
- All strategies (except new UCT) are implemented

Curves (disclaimer: QGB is not fitted, I've just picked some random `C`, hence the poor performance)
![image](https://cloud.githubusercontent.com/assets/6382449/12559520/7918e1b8-c38d-11e5-94b8-d0d4194cf0fa.png)

Times for random experiment per strategy:
![image](https://cloud.githubusercontent.com/assets/6382449/12553208/f38a88e0-c36d-11e5-843d-977387ea1f4d.png)

**Comment by igorsieradzki** [comment]
Valid and Aleph results:
https://gist.github.com/igorsieradzki/4505020233b18aae971b
